### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'.

### ISSUE THREAD

**Issue by farenhite** [ozkc/instagram-unfollowers#1]
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(" ~ Connecting to Instagram")?

pyton 3.6
i edit " ~ Connecting to Instagram" to (" ~ Connecting to Instagram") but another error .......
update it with latest python plz

**Comment by ccozkan** [comment]
try with python2. I updated the readme.md in order to prevent future misunderstandings.
